### ISSUE TITLE
Problems Creating Map Links Suddenly

### ISSUE THREAD

**Issue by ffxivtools** [goatcorp/Dalamud#142]
The following code worked until 2 days ago. Now the code crashes or prints a blank chat entry when wrapped in try/catch. Everything works as it should in debugging. Printing the coordinates in Chat.Print displays the correct values. ffxiv_dx11.exe + 0x1C63F34 shows the correct Map value. I'm not sure if I'm doing something wrong that somehow just worked until the latest version, or if an update broke it. It appears to be referencing Dalamud 5.0.0.2 currently. Here's the affected code:

    var currentActor = this.pluginInterface.ClientState.Actors[i];
    var MapID = (ushort)Marshal.ReadInt16(pluginInterface.TargetModuleScanner.Module.BaseAddress + 0x1C63F34);
    var TerritoryType = pluginInterface.ClientState.TerritoryType;

    XivChatEntry entry = new XivChatEntry() { MessageBytes = new 
    Dalamud.Game.Chat.SeStringHandling.Payloads.MapLinkPayload(TerritoryType, MapID, convertCoord(currentActor.Position.X, 100), 
    convertCoord(currentActor.Position.Y, 100)).Encode(), Type = XivChatType.Echo };````

where convertCoords is:

       public static float convertCoord(double coord, double scale)
        {
            var c = scale / 100.0;
            coord *= c;
            return float.Parse(((41.0 * c) * ((coord + 1024.0) / 2048.0)).ToString("#.#"));
        }

I also the function this way to no avail:

    var currentActor = this.pluginInterface.ClientState.Actors[i];
    var MapID = (ushort)Marshal.ReadInt16(pluginInterface.TargetModuleScanner.Module.BaseAddress + 0x1C63F34);
    var TerritoryType = pluginInterface.ClientState.TerritoryType;

    XivChatEntry entry = new XivChatEntry() { MessageBytes = new 
    Dalamud.Game.Chat.SeStringHandling.Payloads.MapLinkPayload(TerritoryType, MapID, (int)currentActor.Position.X, (int)currentActor.Position.Y).Encode(), Type = XivChatType.Echo };```

**Comment by josephleewilliams** [comment]
This is happening because the Payload class is no longer setting it's DataResolver property in the constructor. Thus the calls inside of MapLinkPayload's constructor that call to the Map property that then use DataResolver to get at the sheets for SizeFactor returns null and throws an error.

This is probably affecting any other Payloads that access the DataResolver since this is set in the base Payload class.

One solution depending on how easy it is to access the DataManager set at the Dalamud level would be to put it back into the Payload constructor.

An alternative solution would be to add a DataManager data argument to each payload that requires it so you would then make your MapLinkPayload call like MapLinkPayload(PluginInterface.Data, territoryType, MapID, x, y)

Asking around to determine what would be the best solution to fix this.

**Comment by ffxivtools** [comment]
Thank you for your assistance

**Comment by goaaats** [comment]
I have since fixed this, will be in the next update for dalamud.
