### ISSUE TITLE
Offer option to scale ImGui

### ISSUE THREAD

**Issue by goaaats** [goatcorp/Dalamud#147]
for big resolutions

**Comment by ff-meli** [comment]
Scaling the actual graphic would.. probably not work well (though I know you did something in the meantime, so maybe that was it?)  Technically this falls to plugin devs since we all hardcode pixel coordinates and sizes, but...

It might just be simplest to have dalamud provide something like the canvas size and/or a scale factor, along with the concept of 1.0x scale probably being 1080 res.

Could also go a step farther and provide methods to give you back scaled coords, to replace math in plugins with method calls.  Neither is really nice to use though.  Not sure of anything directly in imgui to facilitate it though.

Anything more would seem like it'd need a(nother) wrapper layer around 3/4 of imgui, which seems awful.

**Comment by goaaats** [comment]
I implemented this using global font scale, it gets somewhat blurry when you scale it up a ton, but it's probably the best we can do for now.
