### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Ellakai** [goatcorp/Dalamud#1515]
Hello,

I have actually issue with one Dalamud plugin. When i launch the game, the screen is black.
The sound is ok, and i can see the "home screen" in the windows mignature (or with alt+tab).

When i launch Dalamud without pluging, the game is perfectly running.

How i can identify which plugin create this issue ? 
I can of course try do delete pluging by pluging, but i think something better exist ^^

Thanks for your help

**Comment by Ellakai** [comment]
One other point : i copy the full folder in a other computeur, and it's perfectly running (on the second one) :(

**Comment by SayuShira** [comment]
~~Dalamud is still in testing for today's release. Since you can start the game with Dalamud, I assume you are aware and on the beta. If not, just wait until the new stable version releases and try again.~~
The new stable just released. To get it you have to restart the game. Maybe it already fixed itself?

Similar to starting without Dalamud, you can start without Custom Repo plugins. If you use any, the list of plugins that might cause issues is reduced without deleting anything. If you can still see the Dalamud overlay, you can also deactivate plugins instead of deleting them, saving you the hassle to look which ones you had installed previously.

> How i can identify which plugin create this issue ?

There should be a log file under `%appdata%/XIVLauncher` called `dalamud.log`.
The file `dalamud.old.log` is the file from the last login.
You can check there if a plugin is reporting an error.
You can also upload the file. Either here or over at the Dalamud Discord server, where a handy bot can extract some info out of it.
Note:
- The log file might contain your windows username, character info etc.
- Due to the update, the Discord is still in lockdown. Support channels will reopen/reappear some time after the stable build releases

**Comment by Ellakai** [comment]
Thanks for your reply

"you can start without Custom Repo plugins" >> it's also not working
"If you can still see the Dalamud overlay" > i can't see (except when i load without dalamud plugins)

thanks, i will try to resolve my issue with informations shared.

thanks,

**Comment by Ellakai** [comment]
I've identified the source: it's this plugin. After removal, everything is running perfectly.

<img src="https://i.ibb.co/T8Dn6w1/Capture-d-cran-2023-10-31-225154.png">

Thanks again,
regards
