### ISSUE TITLE
"Disable" and add a tooltip for plugins that are not compatible

### ISSUE THREAD

**Issue by lmcintyre** [goatcorp/Dalamud#324]
Almost half the messages in Discord since the 5.5 update have been regarding plugins that have not yet been updated, and why they are *missing* from the plugin installer.

We should list all plugins, but gray-out the ones that are not compatible, with a tooltip with more information, stating something like "This plugin has not yet been updated to work with either the current game version or the current Dalamud version."

**Comment by Aireil** [comment]
That would also list really old plugins that will never be updated. Maybe restrict it to some "popular" ones?

**Comment by reiichi001** [comment]
We could probably add another nag on dalamud updates for new patches (and all Dalamud updates for the following 1-2 weeks) that plugins are still being updated. 

Because a fair sized amount of those people asking are probably not consistently in Goatplace, so they wouldn't be catching our normal FAQs posts and announcements.

**Comment by kalilistic** [comment]
> 
> 
> That would also list really old plugins that will never be updated. Maybe restrict it to some "popular" ones?

Maybe only show the previous version.

**Comment by goaaats** [comment]
We should probably put in some editorial effort for that, and remove/hide plugins that aren't updated anymore.

Would forego the issue.

**Comment by reiichi001** [comment]
This may also lead into some better cleanup of the installedPlugins folder. Perhaps we can also alert if someone has plugins with an API to let them know they should be checking/waiting for an API [current] version? (The issue with telling them to check of course, is that it will lead to just asking in a post. ...there may not be a good way to expose that information without having some curated checklist of plugin update status like "planned to be supported", "awaiting an update", or "discontinued/dropped" etc.

**Comment by AmenneHolelane** [comment]
Could any plugins that weren't updated for 5.4 (or most recent patch minus one) be automated somehow to be removed?

**Comment by AmenneHolelane** [comment]
Manual curation is possible ofc but that would also require someone actively doing it

**Comment by reiichi001** [comment]
I could see us doing something like a permanent API 3 branch method. ...when we make breaking changes or a new client patch comes out, we set up staging branches and then those become the main, rather than merging it into main later. 

It'd also effectively make a history of plugins/plugin versions for specific client releases, should there ever be a need for that.

Like like right now, I'd say we're on the API3_5.5 branch or something. If 5.55 were to break everything again, then it could warrant a new branch. And come 6.0, we'd have our APIx_6.0 branch for Endwalker-compatible plugins (eventually)

**Comment by lmcintyre** [comment]
> 
> 
> > That would also list really old plugins that will never be updated. Maybe restrict it to some "popular" ones?
> 
> Maybe only show the previous version.

I do like this idea, it makes it simple to see that the plugin you installed three days ago is not compatible because it hasn't been update yet. However, I also think it would be interesting to list something like: 

Fantasy Player (outdated) - (hover) > Tooltip text: "This plugin has not been updated for Dalamud API 3. This plugin was last updated on March 7th, 2020."
That would let people know of stale plugins, and give you a time frame of when it will be updated.

Another option could be to add another tab in the installer containing outdated plugins, with the same information as always such as descriptions, but add the last update date and a description as to why it's outdated (API level, game version, etc). That way we aren't cluttering the plugin installer, but also providing as much information as possible to users.

**Comment by goaaats** [comment]
I will work on this

**Comment by daemitus** [comment]
The installed but not applicable task is bleeding over into this. I won't touch the AvailablePlugins tab, but the installed plugins button will change to a disabled "Needs Update"

**Comment by goaaats** [comment]
This is implemented in API4, installed plugins that are outdated will indicate this in the installed plugins tab.
