### ISSUE TITLE
Cleanup for game-version should be lenient, like api level

### ISSUE THREAD

**Issue by daemitus** [goatcorp/Dalamud#440]
case study: sonar specifies the current game version as a manifest requirement. On patch day, the DLL will be cleaned up automatically forcing a manual reinstall.

**Comment by daemitus** [comment]
With the new `GameVersion` type, we can specify something like > 3mo old, cleanup

**Comment by rreminy** [comment]
The reason I'm doing it is because the FATE code have a chance to crash if the signature no longer works anymore. Although I have safeguards in place to automatically disable it one can never be sure so I decided to take this approach. This won't be needed anymore with the .net5 changes however.

Every patch day what my workflow is *(This is only a summary)*:
- Go any zone, check Fates are being read and compare the information displayed
- Find any hunt (usually a B), check its info matches, kill it while looking to make sure its HP is being tracked correctly
- Increment version numbers, match game version, compile and release

**Comment by daemitus** [comment]
implemented
