### ISSUE TITLE
addon inspector crasheroonie

### ISSUE THREAD

**Issue by daemitus** [goatcorp/Dalamud#554]
1. open xldata ai
2. click on jobs in the character window
3. click on "focus units" and open CharacterClass
4. close the character window

It's important to do it with the focused addon dropdown.

@Caraxi would you take a quick look? A lot of this is yours iirc.

Or maybe its time to pull in the new changes from ST.

**Comment by Aireil** [comment]
The addon picker from ST debug in Dalamud would be really nice, if it's easy to copy it over.
The crash also also happens with the ST debug menu. Probably something weird with addons inside addons?

**Comment by Tischel** [comment]
Can confirm this crash happens with a lot of addons.
All you need to do is select the addon and the addon inspector and then close the window in-game.
It happens 100% of times with the "Key Items" window ("InventoryEvent" addon).

I'm pretty sure it's a ImGui crash. Looks like unbalanced push/pop stuff probably due to some null pointer somewhere.

**Comment by Aireil** [comment]
Fixed in #984, I think (only in staging currently).
