### ISSUE TITLE
Feature request: plugins on demand

### ISSUE THREAD

**Issue by Eternita-S** [goatcorp/Dalamud#722]
A feature that would allow user to install plugins but mark them to not load automatically upon game starting. With each game restart user would have to open plugin installer and load plugins that were marked to not autoload. Just like it is with devplugins, basically.

**Comment by daemitus** [comment]
gross

**Comment by PrincessRTFM** [comment]
why

**Comment by daemitus** [comment]
mostly because I just dont want to go back into plugin code :p

**Comment by PrincessRTFM** [comment]
No no, not you. The plugins-on-demand idea. I literally cannot conceive of a _single_ use case in which that would be desirable. If a plugin should only be used at certain times, then ask the author to add a toggle for whatever feature is the issue. Failing that, I could _maybe_ see allowing plugins to be toggled on and off without being removed and reinstalled, though that only applies across game loads. But plugins that just don't load at startup and have to be manually initialised? _Why?_

**Comment by Eternita-S** [comment]
The reason is mostly because of queues and for rather big plugins that can affect game performance/testing plugins that can lead to crashes/other unwanted behavior. Like penumbra for example, I'd only want it running if I'm taking screenshots which is rare, most of the times I don't need it.

**Comment by PrincessRTFM** [comment]
Then... just open the installer and add them when you want them? You'd already have to do that with this idea. You'd save yourself, what, a few seconds of download time by already having the files on your drive, unless there's been an update, in which case you've already had to download the new files anyway.

I'm sorry, maybe I'm misunderstanding, but I can't find any benefit to doing it the way you suggested. Plugins would be downloaded during updates even if not loaded, rather than being downloaded only when wanted. If a plugin affects performance to the degree of not wanting to load it until it's needed, then it sounds like the plugin author should be told, because plugins aren't _supposed_ to affect performance like that. If you're testing a plugin and it causes crashes, then you're requeuing _anyway_ no matter when the crash happens, unless it's before you're even in the queue - IE, at game startup. If you only want a plugin active at certain times, then either only install it at those times, use whatever built-in functionality toggle it has (and I _know_ there's one in Penumbra to turn all mods off), or re-evaluate why you do/don't want it at different times and settle on one.

**Comment by Eternita-S** [comment]
ditch that, I'll just actually later make a plugin that does what I want instead
