### ISSUE TITLE
Custom /Slash commands are not working for ANY plugins, including Dalamud

### ISSUE THREAD

**Issue by EmilyLove26** [goatcorp/Dalamud#853]
None of the /slash commands are working as of the latest update:

### This includes commands from Dalamud itself as well as other Plugins

/xlsettings
/xlhelp
/xlplugins
/xldev
/xpiv - Visibility Plugin
/tweaks
/target <PC> - Simple Tweeks - Fix /Target Command
/pmb - Market Board Plugin

The list is just a sample of what doesn't work, as far as I know, none of the custom /slash commands are working

**Comment by EmilyLove26** [comment]
Seems to be a problem with InnerSpace, not Dalamud. Closing.

**Comment by EmilyLove26** [comment]
A pending pull request

**Comment by LaxLacks** [comment]
I heard about this issue alongside a report that Sonar was also producing Japanese output. This occurs when `DalamudStartupInfo` is not initialized and contains default values, which means `DalamudStartupInfo.Language` is `Japanese` -- the commands are working, they are just in Japanese instead of the expected English in this case.

The referenced commit allows the use of an environment variable `DALAMUD_STARTUP_INFO` to populate the data. This means any injector can load `Dalamud.Boot.dll` without explicitly calling `Initialize`. It will initialize itself if provided.

**Comment by goaaats** [comment]
Closing this because it's user error, not an actual issue
