### ISSUE TITLE
JP IMEs not working since ImGui update 

### ISSUE THREAD

**Issue by smio102** [goatcorp/Dalamud#946]
Since the latest game patch imgui text inputs no longer have input prediction
This makes typing in Japanese very hard as you can't see at all what is being typed.
Using any plugin with significant text input is basically impossible for Japanese players.

**Comment by goaaats** [comment]
What IME are you using?

**Comment by Bluefissure** [comment]
The WndProc hook is using DispatchMessage instead of SetWindowLongPtr to prevent a RivaTuner incompatibility crash, and it causes an incompatible `wParam` and `lParam` while handling imm messages.
Ex, OpenCandidate [should be 0x0005](https://github.com/goatcorp/Dalamud/blob/ac7f3ea/Dalamud/NativeFunctions.cs#L907) but it is 269 in the new hook, so it doesn't trigger any IME window.
I don't know why and how the difference is made, I tried to upgrade my OS to 22H2 (Win11) and the OpenCandidate can be triggered, but the composition-related messages cannot be handled well still.

**Comment by Bluefissure** [comment]
I released a legacy version of my [IMEPlugin](https://github.com/Bluefissure/IMEPlugin/tree/legacy) just now, in case anyone needs it.
`https://raw.githubusercontent.com/Bluefissure/IMEPlugin/legacy/repo.json`

BTW the Dalamud needs to disable the IME handling or there'll be double input https://github.com/ottercorp/Dalamud/commit/0cbb5b7805a6949580d01519e37b52f27788d88d

**Comment by lmcintyre** [comment]
@Soreepeong Is there anything you can do with regards to the RTSS compatibility that maintains IME message support?
